{% set name = "pygubu" %}
{% set version = "0.38" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygubu-{{ version }}.tar.gz
  sha256: f0250e21eca1354b0d6beae2b3352f02d67a798b3abed7fccb1fa1e3c24d29c2

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - importlib-resources  # [py<39]
    - xorg-libx11  # [linux]

test:
  imports:
    - pygubu
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pygubu/
  summary: A simple GUI builder for the python tkinter module
  dev_url: https://github.com/alejandroautalan/pygubu
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - alejandroautalan
